/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\foxEnv.glb --shadows 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Env(props) {
  const { nodes, materials } = useGLTF('/foxEnv.glb')
  materials['Material.001'].color = new THREE.Color(0.2, 0.2, 0.2)

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, 1.227, 0]} scale={-85.364} />
      <mesh castShadow receiveShadow geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0, -74.1, 0]} scale={126.558} />
    </group>
  )
}

useGLTF.preload('/foxEnv.glb')
