/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 garuda.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Garuda(props) {
  const { nodes, materials } = useGLTF('/garuda.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
        <mesh geometry={nodes.Garuda_1.geometry} material={materials.redstripe} />
        <mesh geometry={nodes.Garuda_2.geometry} material={materials.drill} />
        <mesh geometry={nodes.Garuda_3.geometry} material={materials.yellow} />
        <mesh geometry={nodes.Garuda_4.geometry} material={materials.green} />
        <mesh geometry={nodes.Garuda_5.geometry} material={materials.treads} />
        <mesh geometry={nodes.Garuda_6.geometry} material={materials.face} />
      </group>
    </group>
  )
}

useGLTF.preload('/garuda.glb')
