/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tank.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tank(props) {
  const { nodes, materials } = useGLTF('/tank.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
        <mesh geometry={nodes.tank_1.geometry} material={materials.tank} />
        <mesh geometry={nodes.tank_2.geometry} material={materials.silver} />
        <mesh geometry={nodes.tank_3.geometry} material={materials.light} />
        <mesh geometry={nodes.tank_4.geometry} material={materials.orange} />
        <mesh geometry={nodes.tank_5.geometry} material={materials.blue} />
      </group>
    </group>
  )
}

useGLTF.preload('/tank.glb')
